import { Vehicle, Brand, StoreConfig } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'toyota-corolla-2023',
    name: 'Toyota Corolla XEI',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2023,
    price: 125000,
    mileage: 15000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Prata',
    doors: 4,
    image: '/src/assets/cars/corolla.jpg',
    featured: true,
    description: 'Toyota Corolla XEI 2023 em perfeito estado, único dono, todas as revisões em concessionária.',
    specs: {
      engine: '2.0L 16V',
      power: '177 cv',
      torque: '21,4 kgfm',
      consumption: '12,5 km/l',
    },
    features: [
      'Central multimídia',
      'Câmera de ré',
      'Ar condicionado digital',
      'Bancos de couro',
      'Sensor de estacionamento',
      'Controle de cruzeiro',
      'Piloto automático',
      'Faróis em LED',
    ],
  },
  {
    id: '2',
    slug: 'honda-civic-2022',
    name: 'Honda Civic Touring',
    brand: 'Honda',
    model: 'Civic',
    year: 2022,
    price: 145000,
    mileage: 22000,
    fuel: 'Gasolina',
    transmission: 'CVT',
    color: 'Preto',
    doors: 4,
    image: '/src/assets/cars/civic.jpg',
    featured: true,
    description: 'Honda Civic Touring 2022, versão top de linha com todos os opcionais.',
    specs: {
      engine: '1.5L Turbo',
      power: '192 cv',
      torque: '24,5 kgfm',
      consumption: '13,2 km/l',
    },
    features: [
      'Teto solar',
      'Sistema Honda Sensing',
      'Bancos em couro',
      'Central multimídia 9"',
      'Ar condicionado automático',
      'Faróis full LED',
      'Rodas 17"',
      'Carregador wireless',
    ],
  },
  {
    id: '3',
    slug: 'jeep-compass-2021',
    name: 'Jeep Compass Limited',
    brand: 'Jeep',
    model: 'Compass',
    year: 2021,
    price: 135000,
    mileage: 35000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Branco',
    doors: 4,
    image: '/src/assets/cars/compass.jpg',
    featured: false,
    description: 'Jeep Compass Limited 2021, SUV completo e confortável.',
    specs: {
      engine: '2.0L Turbo Diesel',
      power: '170 cv',
      torque: '35,7 kgfm',
      consumption: '11,8 km/l',
    },
    features: [
      'Tração 4x4',
      'Teto panorâmico',
      'Bancos em couro',
      'Central multimídia UConnect',
      'Câmeras 360°',
      'Controle de estabilidade',
      'Ar digital dual zone',
      'Keyless entry',
    ],
  },
  {
    id: '4',
    slug: 'volkswagen-jetta-2020',
    name: 'Volkswagen Jetta',
    brand: 'Volkswagen',
    model: 'Jetta',
    year: 2020,
    price: 95000,
    mileage: 45000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Cinza',
    doors: 4,
    image: '/src/assets/cars/jetta.jpg',
    featured: false,
    description: 'VW Jetta 2020, sedã esportivo e econômico.',
    specs: {
      engine: '1.4L TSI',
      power: '150 cv',
      torque: '25,5 kgfm',
      consumption: '14,1 km/l',
    },
    features: [
      'Central multimídia',
      'Ar condicionado automático',
      'Câmera de ré',
      'Sensor de chuva',
      'Faróis em LED',
      'Controle de cruzeiro',
      'Rodas 17"',
      'Partida sem chave',
    ],
  },
  {
    id: '5',
    slug: 'chevrolet-onix-2023',
    name: 'Chevrolet Onix Premier',
    brand: 'Chevrolet',
    model: 'Onix',
    year: 2023,
    price: 85000,
    mileage: 8000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Vermelho',
    doors: 4,
    image: '/src/assets/cars/onix.jpg',
    featured: true,
    description: 'Chevrolet Onix Premier 2023, praticamente zero km.',
    specs: {
      engine: '1.0L Turbo',
      power: '116 cv',
      torque: '16,8 kgfm',
      consumption: '15,2 km/l',
    },
    features: [
      'MyLink',
      'Ar condicionado automático',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Controle de tração',
      'Faróis em LED',
      'Rodas 16"',
      'OnStar',
    ],
  },
  {
    id: '6',
    slug: 'hyundai-hb20-2022',
    name: 'Hyundai HB20 Platinum',
    brand: 'Hyundai',
    model: 'HB20',
    year: 2022,
    price: 72000,
    mileage: 18000,
    fuel: 'Flex',
    transmission: 'Automático',
    color: 'Azul',
    doors: 4,
    image: '/src/assets/cars/hb20.jpg',
    featured: false,
    description: 'Hyundai HB20 Platinum 2022, completo e econômico.',
    specs: {
      engine: '1.0L Turbo',
      power: '120 cv',
      torque: '17,5 kgfm',
      consumption: '14,8 km/l',
    },
    features: [
      'Central multimídia Bluelink',
      'Ar condicionado automático',
      'Câmera de ré',
      'Controle de cruzeiro',
      'Faróis em LED',
      'Vidros elétricos',
      'Rodas 15"',
      'Direção elétrica',
    ],
  },
];

export const brands: Brand[] = [
  { id: 'toyota', name: 'Toyota', logo: '🔴' },
  { id: 'honda', name: 'Honda', logo: '🔴' },
  { id: 'volkswagen', name: 'Volkswagen', logo: '🔵' },
  { id: 'chevrolet', name: 'Chevrolet', logo: '🟡' },
  { id: 'ford', name: 'Ford', logo: '🔵' },
  { id: 'fiat', name: 'Fiat', logo: '🔴' },
  { id: 'hyundai', name: 'Hyundai', logo: '🔵' },
  { id: 'jeep', name: 'Jeep', logo: '🟢' },
  { id: 'nissan', name: 'Nissan', logo: '⚫' },
  { id: 'renault', name: 'Renault', logo: '🟡' },
  { id: 'peugeot', name: 'Peugeot', logo: '🔵' },
];

export const storeConfig: StoreConfig = {
  name: 'Multimarcas Veículos',
  phone: '(11) 98765-4321',
  whatsapp: '5511987654321',
  email: 'contato@multimarcas.com.br',
  address: 'Av. Principal, 1234 - Centro, São Paulo - SP',
  mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.1975746125896!2d-46.65844268502207!3d-23.561414884681846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce59c8da0aa315%3A0xd59f9431f2c9776a!2sAv.%20Paulista%2C%20S%C3%A3o%20Paulo%20-%20SP!5e0!3m2!1sen!2sbr!4v1234567890123!5m2!1sen!2sbr',
  openingHours: 'Seg-Sex: 9h às 18h | Sáb: 9h às 14h',
  instagram: '@multimarcasveiculos',
  facebook: 'multimarcasveiculos',
};
